// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIlFo9vTHyEfE2ObKPvizwb6mOL0v--s8',
    appId: '1:186749122245:web:6fcd8f0e1bb4ec550562ac',
    messagingSenderId: '186749122245',
    projectId: 'pasartani-21',
    authDomain: 'pasartani-21.firebaseapp.com',
    storageBucket: 'pasartani-21.firebasestorage.app',
    measurementId: 'G-RTZTK3G0XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSN3zoCL4kvRMLURIx4gdZQ31lMIMsFQ',
    appId: '1:186749122245:android:15bbd58a3a1f5ce30562ac',
    messagingSenderId: '186749122245',
    projectId: 'pasartani-21',
    storageBucket: 'pasartani-21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4bAMPglKGgLAKh3OvD-6bzDCpE6bi894',
    appId: '1:186749122245:ios:98762f014885c0630562ac',
    messagingSenderId: '186749122245',
    projectId: 'pasartani-21',
    storageBucket: 'pasartani-21.firebasestorage.app',
    iosBundleId: 'com.example.pasarTaniNelayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4bAMPglKGgLAKh3OvD-6bzDCpE6bi894',
    appId: '1:186749122245:ios:98762f014885c0630562ac',
    messagingSenderId: '186749122245',
    projectId: 'pasartani-21',
    storageBucket: 'pasartani-21.firebasestorage.app',
    iosBundleId: 'com.example.pasarTaniNelayan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIlFo9vTHyEfE2ObKPvizwb6mOL0v--s8',
    appId: '1:186749122245:web:73e3bfe8c5140b390562ac',
    messagingSenderId: '186749122245',
    projectId: 'pasartani-21',
    authDomain: 'pasartani-21.firebaseapp.com',
    storageBucket: 'pasartani-21.firebasestorage.app',
    measurementId: 'G-QWM2SQDQ99',
  );
}
